name: nest
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas=1.6.0
  - scikit-learn=1.6.1
  - imbalanced-learn=0.10.1
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - xgboost=2.1.3
  - shap=0.42.1